### ISSUE TITLE
Troca de licença

### ISSUE THREAD

**Issue by migeyel** [petbccufscar/ufscar-planner#62]
Estamos trocando a licença de direitos autorais do projeto de GPLv3 para MIT para compatibilidade com a Apple App Store. Se você concorda em disponibilizar suas contribuições sob essa nova licença, por favor comente abaixo.

**Comment by migeyel** [comment]
Eu concordo.

**Comment by jobucaldas** [comment]
Eu concordo com a troca da licença

**Comment by OakBranches** [comment]
Eu concordo com a troca da licença

**Comment by isarbela** [comment]
Concordo com a troca da licença.

**Comment by Lucas-Cid** [comment]
Eu concordo.

**Comment by VanderleiJr** [comment]
Concordo!

**Comment by migeyel** [comment]
CC @Lvght @jorgeprj @maluedwards @NataliaBachiega

**Comment by Lvght** [comment]
Eu concordo.

**Comment by NataliaBachiega** [comment]
Eu concordo.

**Comment by maluedwards** [comment]
Eu concordo!

**Comment by jorgeprj** [comment]
Eu concordo!
